<!doctype html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link rel="shortcut icon" href="${resource(dir: 'images', file: 'favicon.ico')}" type="image/x-icon">
	<link rel="stylesheet" id="CssAutoGeneratedCSS-css" href="${resource(dir: 'css', file: 'css-slider-autogenerated.css')}" type="text/css" media="all">
	<link rel="stylesheet" id="child-theme-css" href="${resource(dir: 'css', file: 'style.css')}" type="text/css" media="all">
	<script type="text/javascript" src="${resource(dir: 'js', file: 'jquery.js')}"></script>
	<script type="text/javascript" src="${resource(dir: 'js', file: 'slides.js')}"></script>
	<script type="text/javascript">
		$(document).ready(function() {
			$('#css-slider').slides({
				preload: true,
				generateNextPrev: true,
				generatePagination: true,
				play: 5000,
				pause: 1000,
				hoverPause: true,
				slideSpeed: 700,
				effect: 'slide',
				currentClass: 'active-marker'
			});
			
			$('#css-slider .pagination a, #css-slider a.prev, #css-slider a.next').html('');
		});
	</script>
	<title><g:message code="site.label" /></title>
</head>
<body class="home blog header-image content-sidebar">
<div id="wrap">
	<div id="header">
		<div class="wrap">
			<div id="title-area">
				<h1 id="title"><g:link title="AtYourService" controller="home">AtYourService</g:link></h1>
				<p id="description">Your Reliable Services Network</p>
			</div><!-- end #title-area -->
			<div class="widget-area">
				<div id="text-3" class="widget widget_text">
					<div class="widget-wrap">
						<div class="textwidget">
							<div class="header-right-nav-wrap">
								<ul id="header-right-nav">
									<%--<li><a id="how-it-works-menu-item" href="#">How It Works</a></li> --%>
									<%--<li><a id="list-services-menu-item" href="#">List Your Services</a></li> --%>
									<li><a id="list-services-menu-item" href="/at-your-service/siteUser/create">List Your Services</a></li>
									<sec:ifLoggedIn>
										<li><g:link controller="logout" class="blue-btn"><g:message code="logout.label" /></g:link></li>
									</sec:ifLoggedIn>
									<sec:ifNotLoggedIn>
										<li><g:link controller="login" class="blue-btn"><g:message code="login.label" /></g:link></li>
									</sec:ifNotLoggedIn>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div><!-- end .widget-area -->
		</div><!-- end .wrap -->
	</div><!--end #header-->

	<div id="nav">
		<div class="wrap">
			<ul id="menu-home-menu" class="menu genesis-nav-menu menu-primary superfish sf-js-enabled">
				<li id="menu-item-58" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-58"><a href="#">Cebu’s first premium business directory is coming late 2013.  Register your business now for FREE!</a></li>
			</ul>
		</div><!-- end .wrap -->
	</div>

	<div id="inner">
		<div id="home-top-bg">
			<div id="home-top">
	
				<div class="home-top-left">
					<div id="text-5" class="widget widget_text">
						<div class="textwidget">
							<h1>The smartest way to hire<br>service providers is coming<br>to Cebu City in late 2013</h1>
							<h4>Register your business today and get 3<br>months of our premium service for free!</h4>
						</div>
					</div>
				</div><!-- end .home-top-left -->
		
				<div class="home-top-right form-box">
					<div id="text-4" class="widget widget_text">
						<div class="textwidget"><div class="search-box">
							<g:form controller="search">
								<g:render template="../search/form"/>
								<g:submitButton name="create" value="${message(code: 'default.button.search.label', default: 'Search')}" />
							</g:form>
						</div>
					</div>
				</div>
				</div><!-- end .home-top-right -->
				
			</div><!-- end #home-top -->
		</div><!-- end #home-top-bg -->

		<div id="home-middle-bg">
			<div id="home-middle">
		
				<div class="home-mid-search-cats">
					<h2>Take a sneak peek at our new platform:</h2>
						<ul id="search-cat-wrap">
							<li>
								<a href="#">
									<h4>Contractors</h4>
									<div class="round-cat-bg"><div class="contractors-cat"></div></div>
								</a>
							</li>
							<li>
								<a href="#">
									<h4>Doctors</h4>
									<div class="round-cat-bg"><div class="doctors-cat"></div></div>
								</a>
							</li>
							<li>
								<a href="#">
									<h4>Gardeners</h4>
									<div class="round-cat-bg"><div class="gardeners-cat"></div></div>
								</a>
							</li>
							<li>
								<a href="#">
									<h4>Accountants</h4>
									<div class="round-cat-bg"><div class="accountants-cat"></div></div>
								</a>
							</li>
							<li>
								<a href="#">
									<h4>Lawyers</h4>
									<div class="round-cat-bg"><div class="lawyers-cat"></div></div>
								</a>
							</li>	
							<li>
								<a href="#">
									<h4>Bookkeepers</h4>
									<div class="round-cat-bg"><div class="bookkeepers-cat"></div></div>
								</a>
							</li>
						</ul>
				</div><!-- end .home-mid-search-cats -->
				
		    </div><!-- end #home-middle -->
		</div><!-- end #home-middle-bg -->		

	</div><!-- end of inner -->
		
	<div id="footer-widgeted">
		<div class="wrap">
    	
    		<div class="footer-menus">
        		<div id="nav_menu-3" class="widget widget_nav_menu">
        			<div class="widget-wrap">
        				<h4 class="widgettitle">Sneak Peek</h4>
       					<div class="menu-footer-cats-container">
       						<ul id="menu-footer-cats" class="menu">
       							<li id="menu-item-74" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-74"><a href="#">Accountants</a></li>
								<li id="menu-item-75" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-75"><a href="#">Gardeners</a></li>
								<li id="menu-item-76" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-76"><a href="#">Contractors</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div id="nav_menu-4" class="widget widget_nav_menu">
					<div class="widget-wrap">
						<h4 class="widgettitle">Company</h4>
						<div class="menu-footer-company-container">
							<ul id="menu-footer-company" class="menu">
								<li id="menu-item-79" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-79"><a href="http://184.173.193.62/%7Eays/about">About</a></li>
								<li id="menu-item-77" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-77"><a href="http://184.173.193.62/%7Eays/our-story">Our Story</a></li>
								<li id="menu-item-78" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-78"><a href="http://184.173.193.62/%7Eays/contact">Contact</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div id="nav_menu-5" class="widget widget_nav_menu">
					<div class="widget-wrap">
						<h4 class="widgettitle">Support</h4>
						<div class="menu-footer-support-container">
							<ul id="menu-footer-support" class="menu">
								<li id="menu-item-81" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-81"><a href="http://184.173.193.62/%7Eays/frequent-questions">Frequent Questions</a></li>
								<li id="menu-item-80" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-80"><a href="http://184.173.193.62/%7Eays/terms-of-service">Terms of Service</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div id="nav_menu-6" class="widget widget_nav_menu">
					<div class="widget-wrap">
						<h4 class="widgettitle">Connect</h4>
						<div class="menu-footer-social-container">
							<ul id="menu-footer-social" class="menu">
								<li id="menu-item-82" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-82"><a href="#">Facebook</a></li>
								<li id="menu-item-83" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-83"><a href="#">Twitter</a></li>
							</ul>
						</div>
					</div>
				</div>
	 
	   		</div><!-- end .footer-menus -->
    	
    		<div class="footer-credits">
        		<div id="text-7" class="widget widget_text">
        			<div class="widget-wrap">
        				<div class="textwidget">
        					<g:link controller="home"><img src="${resource(dir: 'images', file: 'misc/footer-logo-a.png')}" alt="AtYourService Logo"></g:link>
							<p>© Copyright 2013 AtYourService<br>All rights reserved.</p>
						</div>
					</div>
				</div>
    		</div><!-- end .footer-credits -->

		</div><!-- end .wrap -->
	</div><!-- end #footer-widgeted -->

	<div id="start-service-signup" class="hidden page-dim">
		<div class="wrap">
			<div class="form-wrap">
				<div class="close-btn-wrap">
					<a class="close-btn">Close</a>
				</div>
				<div class="form-header">
					<h2>Welcome to<span class="text-indent">AtYourService</span></h2>
					<span class="signup-logo"></span>
					<p>Listing your services is fast, easy and free.</p>
					<p class="directions"><span class="left-down-arrow down-arrow"></span>Get Started Below:<span class="right-down-arrow down-arrow"></span></p>
				</div>
				<div class="form-body">
					<g:form controller="siteUser" action="save">
						<ul>
							<li class="hidden"><input name="primary_city" type="hidden"></li>
							<li class="hidden"><input name="secondary_city" type="hidden"></li>
							<li class="half-field inline">
								<input name="first_name" value="First name" type="text" required=""></input>
								<input name="last_name" value="Last name" type="text" required=""></input>
							</li>
							<li class="full-field"><input name="company_name" value="Company name" type="text"></li>
							<li class="full-field title-position-input inner-note-container">
								<input class="has-inner-note" name="title_position" value="Title / Position" type="text">
							</li>
							<%--
							<li class="full-field phone-number-input inner-note-container">
								<input class="has-inner-note" name="phone_number_1" value="Phone number" type="text">
								<p class="input-description">Format: 0915-234-7890 OR 412-1234</p>
							</li>
							 --%>
							<li class="full-field email-input inner-note-container">
								<input class="has-inner-note" name="email-primary" value="Email" type="text" required=""></input>
								<p class="input-description">This will also be your username</p>
							</li>
							<!-- *** EMAIL will be username ***					
							<li class="full-field username-input inner-note-container">
								<input class="has-inner-note" name="username" type="text" value="Username" >
								<span class="inside-field-note">may contain letters and numbers only</span>
							</li> 
							-->
							<li class="half-field inline">
								<input name="password" value="Password" type="text" required=""></input>
								<input name="confirm_password" value="Confirm Password" type="text" required=""></input>
							</li>
							<li class="service-terms"><input name="confirm_service_terms" type="checkbox"><span>I have read and accept the <a href="#">terms of service</a>.</span></li>
							<!-- <li><a href="http://184.173.193.62/%7Eays/app/step-1-categories-and-offerings.html" class="biz-pop-up-submit">Create My FREE Account</a></li> -->						
							<li><input class="biz-pop-up-submit" name="submit" type="submit" value="Create My FREE Account"></li>
						</ul>
					</g:form>
				</div>
			</div><!-- end .form-wrap -->
		</div><!-- end .wrap -->
	</div><!-- end #start-service-signup -->

</div><!-- end #wrap -->
<script type="text/javascript" src="${resource(dir: 'js', file: 'front.js')}"></script>
<script type="text/javascript" src="${resource(dir: 'js', file: 'superfish.js')}"></script>
<script type="text/javascript" src="${resource(dir: 'js', file: 'superfish_002.js')}"></script>
</body>
<%--
<body>
	<div class="container-fluid search-container">
		<div class="container">
			<div class="row-fluid">
				<div class="span6">
			    	<h2>The smart way to hire services in Cebu City</h2>
			    	<blockquote class="quote-home">Start finding trusted contractors, professionals and skilled workers for free!</blockquote>
			   	</div>
			   	<div class="span6">
					<div class="content scaffold-create" role="main">
						<div role="search" class="searchform">
							<g:form controller="search">
								<fieldset class="form">
									<g:render template="../search/form"/>
								</fieldset>
								<fieldset class="buttons">
									<g:submitButton name="create" class="save btn btn-large btn-block btn-primary" value="${message(code: 'default.button.search.label', default: 'Search')}" />
								</fieldset>
							</g:form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="container-fluid">
		<div class="container sub-content">
			<h3>View Cebu's finest:</h3>
			<ul class="circular-menu">
				<li><h4><g:message code="template.search.contractors" /></h4>
					<g:link class="circle-icon" controller="search" action="search" params="[category:'contractors']"><img src="<g:resource dir="images" file="icon-house.png" />" /></g:link>
					<g:link controller="search" action="search" params="[category:'contractors']"><g:message code="search.label" /></g:link>
				</li>
				<li><h4><g:message code="template.search.doctors" /></h4>
					<g:link class="circle-icon" controller="search" action="search" params="[category:'doctors']"><img src="<g:resource dir="images" file="icon-medical.png" />" /></g:link>
					<g:link controller="search" action="search" params="[category:'doctors']"><g:message code="search.label" /></g:link>
				</li>
				<li><h4><g:message code="template.search.gardeners" /></h4>
					<g:link class="circle-icon" controller="search" action="search" params="[category:'gardeners']"><img src="<g:resource dir="images" file="icon-plant.png" />" /></g:link>
					<g:link controller="search" action="search" params="[category:'gardeners']"><g:message code="search.label" /></g:link>
				</li>
				<li><h4><g:message code="template.search.accountants" /></h4>
					<g:link class="circle-icon" controller="search" action="search" params="[category:'accountants']"> <img src="<g:resource dir="images" file="icon-table.png" />" /></g:link>
					<g:link controller="search" action="search" params="[category:'accountants']"> <g:message code="search.label" /></g:link>
				</li>
				<li><h4><g:message code="template.search.lawyers" /></h4>
					<g:link class="circle-icon" controller="search" action="search" params="[category:'lawyers']"><img src="<g:resource dir="images" file="icon-judge.png" />" /></g:link>
					<g:link controller="search" action="search" params="[category:'lawyers']"><g:message code="search.label" /></g:link>
				</li>
				<li><h4><g:message code="template.search.bookkeepers" /></h4>
					<g:link class="circle-icon" controller="search" action="search" params="[category:'bookkeepers']"><img src="<g:resource dir="images" file="icon-books.png" />" /></g:link>
				 	<g:link controller="search" action="search" params="[category:'bookkeepers']"><g:message code="search.label" /></g:link>
				</li>
			</ul>
		</div>
	</div>
</body>
 --%>
</html>
